### ISSUE TITLE
Add healthchecks

### ISSUE THREAD

**Issue by tylerpace** [barmiro/SYSH#2]
It would be great if you could suggest a container healthcheck for `sysh` and/or expose a health or status endpoint.

I'm using a standard healthcheck for `postgres` (example below) but I couldn't would out something suitable for `sysh`.

```
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 30s
```
