### ISSUE TITLE
Add ability to rename postgres container

### ISSUE THREAD

**Issue by tylerpace** [barmiro/SYSH#3]
SYSH current hardcodes the name of the `postgres` container but it'd be nice to allow for renaming. SYSH server could accept an ENV VAR that has the postgres container name instead of a hardcoded value.

e.g.,

```
sysh:
    container_name: sysh
    image: barmiro/sysh-server:latest
    environment:
      POSTGRES_CONTAINER: sysh-postgres
      ...

  sysh-postgres:
    container_name: sysh-postgres
    image: barmiro/sysh-postgres:latest
    ...
```
